"""Stage 12 — validate: integrity and schema checks, target-export checks, manifest.json (written last, atomically), report.html."""
from __future__ import annotations

import hashlib
import json
from importlib import resources

import numpy as np

from .. import PIPELINE_VERSION, SCHEMA_VERSION
from ..coords import enu_to_ue, ue_to_enu
from ..gltf import read_glb_json
from ..pipeline import BuildContext
from .common import load_route

# Excluded from the content hash: live weather and build logs (timings)
NON_DETERMINISTIC = {"weather.json", "climatology.json", "build_log.json", "report.html", "manifest.json", ".state.json", "chunks/status.json",
                     "manifest.partial.json", "files.json"}


class ValidationError(RuntimeError):
    pass


def content_hash(ctx: BuildContext) -> tuple[str, list[dict]]:
    files = []
    for p in sorted(ctx.dir.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(ctx.dir).as_posix()
        if rel in NON_DETERMINISTIC or "/." in "/" + rel or rel.startswith("."):
            continue
        h = hashlib.sha256(p.read_bytes()).hexdigest()
        files.append({"path": rel, "bytes": p.stat().st_size, "sha256": h})
    agg = hashlib.sha256("\n".join(f"{f['path']} {f['sha256']}" for f in files).encode()).hexdigest()
    return agg, files


def build_manifest(ctx: BuildContext) -> dict:
    meta = ctx.read_json("route_meta.json")
    wm = ctx.read_json("wind_meta.json")
    seg = ctx.read_json("segments.json")
    im = ctx.read_json("instances_meta.json")
    terrain = ctx.read_json("terrain.json")
    origin = ctx.read_json("origin.json")
    origin["frame"] = "local transverse Mercator at origin (≈ENU), z orthometric"
    info = ctx.read_json("ingest.json")
    if ctx.path("chunks/index.json").exists():
        chunks = ctx.read_json("chunks/index.json")["chunks"]
        chunks = [{k: c[k] for k in ("id", "sStart", "sEnd", "status", "lod", "origin", "lodDistancesM")} for c in chunks]
        far = "far_terrain.glb" if ctx.path("far_terrain.glb").exists() else None
    else:
        from .common import chunk_ranges
        chunks = [{"id": k, "sStart": a, "sEnd": b, "status": "quick", "lod": []} for k, a, b in chunk_ranges(meta["stats"]["distanceM"], ctx.config.tunables.chunk_length_m)]
        far = None
    attribution = []
    for st, srcs in ctx.state.get("sources", {}).items():
        for v in srcs.values():
            if v.get("attribution") and v["attribution"] not in attribution:
                attribution.append(v["attribution"])
    if not attribution:
        attribution = ["Generated by gpx2course"]
    exports = {}
    if ctx.path("web/manifest.json").exists():
        exports["web"] = "web/manifest.json"
    if ctx.path("unreal/course_ue.json").exists():
        exports["unreal"] = "unreal/course_ue.json"
    warnings = [{"stage": st, **w} for st, ws in ctx.state.get("warnings", {}).items() for w in ws]
    return {
        "schemaVersion": SCHEMA_VERSION, "courseId": ctx.course_id, "name": info["name"], "pipelineVersion": PIPELINE_VERSION,
        "tier": ctx.options.tier, "eventStart": ctx.options.event_start.isoformat() if ctx.options.event_start else None,
        "origin": origin, "stats": meta["stats"],
        "route": {"file": "route.bin", "sampleSpacingM": meta["sampleSpacingM"], "count": meta["count"], "arrays": meta["arrays"],
                  "headingConvention": "compass bearing, radians clockwise from north", "radiusInfinite": "Infinity for straight road"},
        "wind": {"file": "wind.bin", "sampleSpacingM": wm["sampleSpacingM"], "count": wm["count"], "directionBins": wm["directionBins"],
                 "layers": wm["layers"], "encoding": wm["encoding"], "layout": wm["layout"], "month": wm["month"], "leafOn": wm["leafOn"]},
        "segments": {"file": "segments.json", **{k: seg[k] for k in ("climbs", "corners", "laps", "pois", "surfaceRuns")}},
        "terrain": {"quickTier": terrain},
        "chunks": chunks, "farField": far,
        "instances": {"file": "instances.bin", "categories": im["categories"], "count": im["count"], "recordBytes": im["recordBytes"],
                      "fields": im["fields"]},
        "quick": {"buildings": "quick/buildings.json", "roads": "quick/roads.json", "water": "quick/water.json"},
        "materialCatalogue": "materials.json", "exports": exports,
        "weather": {"file": "weather.json"}, "climatology": {"file": "climatology.json"},
        "attribution": attribution, "elevationSources": meta.get("elevationSources", []), "barometric": meta.get("barometric"),
        "warnings": warnings,
        **({"riderDefaults": ctx.options.rider} if ctx.options.rider else {}),
    }


def write_partial_manifest(ctx: BuildContext) -> None:
    """Progressive streaming: a manifest the client can ride with while the full bake continues (spec §2, §10.1)."""
    try:
        m = build_manifest(ctx)
    except FileNotFoundError:
        return
    m["partial"] = True
    m["contentHash"] = "0" * 64
    ctx.write_json("manifest.partial.json", m, indent=None)


def check_integrity(ctx: BuildContext, m: dict) -> list[str]:
    errs = []
    n = m["route"]["count"]
    size = sum(n * (4 if a["type"] == "float32" else 1) for a in m["route"]["arrays"])
    if ctx.path("route.bin").stat().st_size != size:
        errs.append("route.bin size does not match count × array sizes")
    w = m["wind"]
    if ctx.path("wind.bin").stat().st_size != w["count"] * w["directionBins"] * len(w["layers"]):
        errs.append("wind.bin size mismatch")
    if ctx.path("instances.bin").stat().st_size != m["instances"]["count"] * m["instances"]["recordBytes"]:
        errs.append("instances.bin size mismatch")
    r = load_route(ctx)
    if not np.all(np.diff(r["s"]) > 0):
        errs.append("route s is not strictly increasing")
    if not np.all(np.isfinite(r["z"])):
        errs.append("route has non-finite elevations")
    for c in m["chunks"]:
        for f in c["lod"]:
            p = ctx.path(f)
            if not p.exists():
                errs.append(f"missing chunk file {f}")
                continue
            try:
                read_glb_json(p.read_bytes())
            except Exception as ex:  # noqa: BLE001
                errs.append(f"invalid GLB {f}: {ex}")
    for t in m["terrain"]["quickTier"]["tiles"]:
        if not ctx.path(f"dem/{t['i']}_{t['j']}.png").exists():
            errs.append(f"missing DEM tile {t['i']}_{t['j']}")
    return errs


def check_exports(ctx: BuildContext, m: dict) -> list[str]:
    errs = []
    if "unreal" in ctx.options.targets:
        if "unreal" not in m["exports"]:
            errs.append("unreal export missing")
        else:
            from PIL import Image
            from .export_unreal import UE_RECOMMENDED
            ue = ctx.read_json("unreal/course_ue.json")
            for t in ue["landscape"]["tiles"]:
                with Image.open(ctx.path("unreal/" + t["heightmap"])) as im:
                    if im.size[0] not in UE_RECOMMENDED or im.size[0] != im.size[1] or im.mode not in ("I;16", "I;16B", "I"):
                        errs.append(f"{t['heightmap']}: not a square 16-bit heightmap of a recommended size")
            r = load_route(ctx)
            back = ue_to_enu(*enu_to_ue(r["x"], r["y"], r["z"]))
            err = max(np.abs(back[0] - r["x"]).max(), np.abs(back[1] - r["y"]).max(), np.abs(back[2] - r["z"]).max())
            if err >= 0.001:
                errs.append(f"ENU→UE→ENU round trip error {err * 1000:.3f} mm ≥ 1 mm")
    if "web" in ctx.options.targets and ctx.options.tier == "full" and "web" not in m["exports"]:
        errs.append("web export missing")
    return errs


def run(ctx: BuildContext) -> list[str]:
    import jsonschema

    m = build_manifest(ctx)
    errs = check_integrity(ctx, m) + check_exports(ctx, m)
    h, files = content_hash(ctx)
    m["contentHash"] = h
    schema = json.loads(resources.files("gpx2course").joinpath("schema/manifest.schema.json").read_text())
    try:
        jsonschema.validate(m, schema)
    except jsonschema.ValidationError as ex:
        errs.append(f"schema: {ex.message} at {'/'.join(map(str, ex.absolute_path))}")
    if errs:
        raise ValidationError("; ".join(errs))
    ctx.write_json("files.json", {"contentHash": h, "files": files}, indent=None)
    from ..report import write_report
    write_report(ctx, m)
    ctx.write_json("manifest.json", m, indent=1)  # last, atomic
    ctx.path("manifest.partial.json").unlink(missing_ok=True)
    return ["manifest.json", "report.html", "files.json"]


def validate_package(path) -> list[str]:
    """Standalone validation of an existing package directory (gpx2course validate)."""
    import jsonschema
    from pathlib import Path

    d = Path(path)
    errs = []
    mp = d / "manifest.json"
    if not mp.exists():
        return ["manifest.json missing (build incomplete?)"]
    m = json.loads(mp.read_text())
    schema = json.loads(resources.files("gpx2course").joinpath("schema/manifest.schema.json").read_text())
    try:
        jsonschema.validate(m, schema)
    except jsonschema.ValidationError as ex:
        errs.append(f"schema: {ex.message}")
    fl = json.loads((d / "files.json").read_text()) if (d / "files.json").exists() else {"files": []}
    for f in fl["files"]:
        p = d / f["path"]
        if not p.exists():
            errs.append(f"missing {f['path']}")
        elif hashlib.sha256(p.read_bytes()).hexdigest() != f["sha256"]:
            errs.append(f"checksum mismatch {f['path']}")
    agg = hashlib.sha256("\n".join(f"{f['path']} {f['sha256']}" for f in fl["files"]).encode()).hexdigest()
    if fl["files"] and agg != m.get("contentHash"):
        errs.append("contentHash does not match files.json")
    for c in m.get("chunks", []):
        for f in c.get("lod", []):
            if not (d / f).exists():
                errs.append(f"missing chunk {f}")
    return errs
